In [3]:
## libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

## veri setini import ediyoruz, ayrac olarak noktalı virgul oldugu için belirtiyoruz.

data = pd.read_csv("multilinearregression.csv", sep = ";")

In [4]:
data

alan  odasayisi  binayasi   fiyat
0   180          5        10  510000
1   225          4        18  508000
2   260          3         2  548000
3   320          6        10  650000
4   335          4         9  628000
5   345          5        14  632000
6   355          3         0  680000
7   400          4        10  725000

In [7]:
x = data[["alan", "odasayisi", "binayasi"]]  ##independent variables
y = data["fiyat"]   ## dependent variables

In [10]:
x = data[["alan", "odasayisi", "binayasi"]]
x

alan  odasayisi  binayasi
0   180          5        10
1   225          4        18
2   260          3         2
3   320          6        10
4   335          4         9
5   345          5        14
6   355          3         0
7   400          4        10

In [27]:
y = data["fiyat"]
y

0    510000
1    508000
2    548000
3    650000
4    628000
5    632000
6    680000
7    725000
Name: fiyat, dtype: int64

In [28]:
reg = linear_model.LinearRegression()

reg.fit(x, y)

reg.predict([[340, 4, 8]])

C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([647546.51344512])

In [29]:
## linear regression modeli tanımlıyoruz

reg = linear_model.LinearRegression()

reg.fit(data[["alan", "odasayisi", "binayasi"]], data["fiyat"])

## prediction yapalım.

reg.predict([[275, 3, 11]])



C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([558597.7242505])

In [30]:
reg.predict([[230, 4, 10]])

C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([530243.29284619])

In [31]:
reg.predict([[230, 6, 0]])

C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([586097.7833456])

In [32]:
reg.predict([[355, 3, 20]])

C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([616657.45791365])

In [33]:
reg.predict([[238, 3, 5], [450, 7, 0], [80, 2, 39]])

C:\Users\90531\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([536534.87983249, 825171.31109341, 272012.00246687])

In [34]:
reg.coef_   ## y = a + b1X1 + b2X2 + ...   katsayıları hesaplar.

array([ 1018.99865454, 14893.82374984, -2606.68429997])

In [35]:
reg.intercept_  ## sabit degeri hesaplar

262365.1503032055

In [36]:
## y = a + b1X1 + b2X2 + b3X3 + ...  

a = reg.intercept_
b1 = reg.coef_[0]
b2 = reg.coef_[1]
b3 = reg.coef_[2]

x1 = 238   ## kontrol için yapıldı
x2 = 3
x3 = 5

y = a + b1 * x1 + b2 * x2 + b3 * x3

y

536534.8798324948